APP_HASH_KEY	: efdef48826ce946501bded462050c0754e99409a
APP_NAME		: ant-dict
APP_DEBUG		: true
APP_TIMEZONE	: Asia/Shanghai
APP_ENV			: development

USER			: admin
PASSWORD		: hello123

ADDRESS         : 0.0.0.0
PROT            : 9999

LOG_DEBUG		: true
LOG_PATH		: logs
LOG_LEVEL		: debug
LOG_FILE		: sys-log.log
LOG_SIZE		: 1048576

DB_CONNECTION	: mysql
DB_HOST			: 127.0.0.1 
DB_PORT			: 3306
DB_DATABASE		: Ant-Dict
DB_USERNAME		: ant-dict
DB_PASSWORD		: hello123
DB_CHARSET		: utf8
